[project]
name = "user-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=4.3.0",
    "fastapi[all]>=0.115.13",
    "ruff>=0.12.0",
    "sqlalchemy>=2.0.41",
]
